version: '3'
services:
  php-devops:
    image: php-devops
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    environment:
      PHP_IDE_CONFIG: serverName=inpi-devops-docker
    networks: 
      - devops
      
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./:/var/www/html:ro
      - ./docker/symfony_vhost.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8010:80
    networks: 
      - devops
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spacewichseo
      MYSQL_USER: spacewich
      MYSQL_PASSWORD: spacewich
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306
    command: "mysqld --character-set-server=utf8mb4 --max_allowed_packet=32M"
    networks: 
      - devops
volumes:
  mysql_data:

networks:
  devops: