name: PHP Composer

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # linter
    - uses: michaelw90/PHP-Lint@master
  security-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # security-checker
    - uses: symfonycorp/security-checker-action@v2
  phpcpd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #php copy paste detector
    - name: PHP Duplicated Code Detector
      uses: StephaneBour/actions-php-cpd@1.0
      with:
        dir: './src'
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - name: CP .env.ci
        run: cp .env.ci .env.local
      - name: Installation des dépendances composer
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: PHPUnit (php-actions)
        uses: php-actions/phpunit@v9
  validate-composer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validation du composer.json et du composer.lock
      run: composer validate
    - name: PHP Version
      run: php -v
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-php@master
        with:
          php-version: '7.3'

      - name: CP .env.ci
        run: cp .env.ci .env.local
      - name: Installation des dépendances composer
        run: composer install --prefer-dist --no-progress --no-suggest
      
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # yarn install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: encore dev # yarn encore dev

