name: PHP Composer

on: pull_request

jobs:
  install-composer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validation du composer.json et du composer.lock
      run: composer validate
    - name: PHP Version
      run: php -v
  build:
    runs-on: ubuntu-latest
    needs: [install-yarn]
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-php@master
        with:
          php-version: '7.3'

      - name: CP .env.ci
        run: cp .env.ci .env.local
      - name: Installation des dépendances composer
        run: composer install --prefer-dist --no-progress --no-suggest
      
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # yarn install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: encore dev # yarn encore dev

