name: PHP Composer

on: pull_request

jobs:
  install-composer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validation du composer.json et du composer.lock
      run: composer validate

  install-yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # yarn install
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installation des dépendances composer
        run: composer install --prefer-dist --no-progress --no-suggest
      
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: encore dev # yarn encore dev
  db-seeding:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Shutdown Default Ubuntu MySQL
          run: sudo service mysql stop
        
        - name: "Setup MySQL"
          uses: mirromutth/mysql-action@v1.1
        
        - name: "Seed Database"
          run: "php bin/console doctrine:schema:update --force" 
